openapi: "3.0.0"
info:
  description: "preferences skill"
  version: "0.0.1"
  title: "preferences-skill"
  termsOfService: "http://swagger.io/terms/"
  license:
    name: "GPLv2"
    url: "https://www.gnu.org/licenses/gpl-2.0.en.html"

servers:
  - url: /api/v1
    description: "The APIs base path"

tags:
- name: "request"
  description: "A request to a monitoring entity"

paths:
  /request:
    post:
      tags:
      - "request"
      summary: "Input a skill request"
      description: ""
      operationId: "api.skill.request"
      requestBody:
        description: "Skill request"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/skillRequestPayload"
      responses:
        200:
          description: "Skill response"
          content:
            application/json:
              schema:
                type: object


components:
  schemas:
    skillRequestPayload:
      required:
       - "type"
       - "payload"
       - "user"
      properties:
        type:
          type: "string"
          example: "get_user_pref"
        user:
          type: "string"
        payload:
          type: "object"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"

